# Site settings
destination: ../austinhay.github.io
title: Austin A. Hay	
email: austin@austinhay.com
description: > 
  This website and all its content, design and code are ©2014 Austin Hay. Questions, comments, consulting inquiry, or anything else? Shoot me an email.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.austinhay.com/" # the base hostname & protocol for your site
twitter_username: austinahay	
github_username:  austinhay
linkedin_username: austinhay

career_title1: "Engineer"
career_title2: "Biz Ops Analyst"
career_title3: "Web-dev Junior Programmer"
career_title4: "Stanford & USC Grad"

career_descriptors: "Engineering Management, Business Operations & Development, Computer Programming, Software, Web-Development, High-tech Strategy, Product Design, Social Impact, Sanitation, WASH, Social Entrepreneurship"

language_descriptors: "I code in...  Ruby, Python, JavaScript, jQuery, Coffeescript, SASS, HAML, AJAX, HTML, CSS, SQL, Git, Source Control, Django, Rails, Sinatra."
# Build settings
markdown: kramdown
